import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "sonner";

import Provider from "./provider";
import {
  SidebarHeader,
  SidebarGroup,
  SidebarContent,
  SidebarFooter,
  Sidebar,
  SidebarProvider,
  SidebarTrigger,
} from "./_components/ui/sidebar";
import { AppSidebar } from "./_components/appSidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} tracking-wide leading-loose`} suppressHydrationWarning>
      <body>
        <Provider>
          <SidebarProvider defaultOpen={false}>
            <AppSidebar
              chats={[
                ...Array.from({ length: 30 }, (_, i) => ({
                  name: `My Chat Is Pretty Veryyyyy Long ${i + 1}`,
                  id: `chat-${i + 1}`,
                })),
              ]}
            />

            <main className="w-full h-screen">
              <SidebarTrigger />

              {children}
            </main>
          </SidebarProvider>
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
